spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台 SQL 日志打印
    map-underscore-to-camel-case: true  #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
  global-config:
    db-config:
      id-type: assign_id #如果不设置类型值，默认则使用IdType.ASSIGN_ID策略（自3.3.0起）。
      #该策略会使用雪花算法自动生成主键ID，主键类型为长或字符串（分别对应的MySQL的表字段为BIGINT和VARCHAR）
raggie:
  path: D:\temp\upload\